// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using astrofleet_service.Data;

#nullable disable

namespace astrofleet_service.Migrations
{
    [DbContext(typeof(AstroFleetDbContext))]
    [Migration("20250517161010_SatelliteBase")]
    partial class SatelliteBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("astrofleet_service.satellites.Entities.Satellite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("ElevationInKilometers")
                        .HasColumnType("double");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HomePlanet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("MassInKilograms")
                        .HasColumnType("double");

                    b.Property<DateTime>("OrbitStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrbitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Satellites");
                });
#pragma warning restore 612, 618
        }
    }
}
