// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using astrofleet_service.Data;

#nullable disable

namespace astrofleet_service.Migrations
{
    [DbContext(typeof(AstroFleetDbContext))]
    [Migration("20250516190717_SatelliteMigration1")]
    partial class SatelliteMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("astrofleet_service.satellites.Entities.Satellite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("ElevationInKilometers")
                        .HasColumnType("double");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("MassInKilograms")
                        .HasColumnType("double");

                    b.Property<DateTime>("OrbitStartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrbitType")
                        .HasColumnType("int");

                    b.Property<string>("SatelliteType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Satellite");

                    b.HasDiscriminator<string>("SatelliteType").HasValue("Satellite");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("astrofleet_service.satellites.Entities.ScientificSatellite", b =>
                {
                    b.HasBaseType("astrofleet_service.satellites.Entities.Satellite");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Scientific");
                });
#pragma warning restore 612, 618
        }
    }
}
